### ISSUE TITLE
Neutrinos and IGRB data missing

### ISSUE THREAD

**Issue by nj-vs-vh** [carmeloevoli/The_CR_Spectrum#5]
Seems like in the last (2024) version of the plot, $\nu + \bar \nu$ and $\gamma$ IGRB data are missing, but the captions are still there.

**Comment by carmeloevoli** [comment]
Thanks for noticing. In fact as I'm rewriting the code, I took profit to add only well referenced datasets. And I realized that I can't remember where I found the gamma-ray data. I'm working on it.
